#!/bin/bash
#
#  THIS IS ECHO SERVER : 
#    socat SYSTEM:./eecho TCP-LISTEN:11111,reuseaddr,fork  NOT very
#    socat EXEC:./eecho TCP-LISTEN:11111,reuseaddr,fork
#    socat EXEC:./eecho TCP-LISTEN:11111,fork NOT GOOD
#
#
#     when echo | nc,  broken pipe frequently....
#    socat EXEC:./eecho TCP-LISTEN:11111,reuseaddr,fork,crlf
#    nc localhost 11111
#     echo `date` | nc -q 1  localhost 11111  SOLVES broken pipe
#
#
#
for (( i=0;i<99999;i++ )); do
  printf "%d> " $i
  read -p "" A
  echo "   " you said \"$A\"
done
