#!/bin/bash

curdir=${PWD##*/}
currentdir=`pwd`
if [ "$curdir" = "offline" ]; then
    echo ____________ branch is network ______________________
else
    echo ____________ branch is memory ______________________
fi

ls -1hl ~/RUN*
DIR=`zenity --file-selection --title="Select directory with RUN" --directory`

if [ "$DIR" = "" ]; then
    echo no directory selected... ending...
  exit;
fi

echo selected : $DIR
BASE=`basename $DIR`

RUNNUM=`echo $BASE | perl -ne 's/.+(0_\d+)/$1/e;print' `

echo basename=$BASE
echo and RUN=$RUNNUM
echo  in $DIR
cd $DIR
SIZE=` du -bs *_u | cut  -f 1 | awk '{total = total + $1}END{printf("%d",total)}'`
###SIZE=$(( $SIZE / 2 ))
echo SIZE of _u files is $SIZE
if [ "$SIZE" = "0" ]; then\
       echo .. this could be due to bz2 files
       SIZE=` du -bs *_u.bz2 | cut  -f 1 | awk '{total = total + $1}END{printf("%d",total)}'`
       echo ... so I tried _u.bz2  ....size = $SIZE
       echo ... i could try to bunzip2 all these ... later
            sleep 2

fi
echo .

DESTFILE=~/RUN$RUNNUM


SIZEnew=`stat -c %s  ~/RUN$RUNNUM`
if [ "$SIZEnew" = "0" ]; then
    echo ZERO SIZE ~/RUN$RUNNUM I REMOVE
    ls -l ~/RUN$RUNNUM
    echo =====================================
    rm -i ~/RUN$RUNNUM
fi



echo copying to  $DESTFILE ...

if [ -e $DESTFILE ]; then
 echo file already exists !
 SIZEOLD=`stat -c %s $DESTFILE`
 echo size dir $SIZE / $SIZEOLD = size file
 if [ $SIZE = $SIZEOLD ]; then
     echo the file is probably the same size
     echo .           ok    
     echo .
 else
     echo Not the same sizes !!!
     echo I prefer to use an old file $DESTFILE
     echo =====================================
     sleep 2
 fi

else
    if [ -e $DESTFILE.bz2 ]; then
	echo maybe file is already bzipped ............
	ls -lh $DESTFILE.bz2
	echo .
	echo press enter to bunzip2 $DESTFILE.bz2
	read
	echo bunzipping
#####	pbunizp2 -v  $DESTFILE.bz2
	bunzip2 -v $DESTFILE.bz2
    else
	echo COPYING RAW ALL FILES =================================================
	ls -1tr *.vme_u | xargs -I III cat III  | pv -s $SIZE -L 190M > ~/RUN$RUNNUM
	SIZEnew=`stat -c %s  ~/RUN$RUNNUM`
	if [ "$SIZEnew" = "0" ]; then
	    echo NO DATA COPIED ... I try to bunzip `ls -1 *.vme_u.bz2 |wc -l` .vme_u.bz2 files
	    sleep 2
	    rm -i ~/RUN$RUNNUM
	    touch ~/RUN$RUNNUM
	    ls -1tr *.vme_u.bz2 | xargs -I III bunzip2 -c III  | pv -s $SIZE -L 190M >> ~/RUN$RUNNUM
	    echo LOOK:
	    ls -lthr  ~/RUN$RUNNUM
	fi
    fi
fi





########################################################### FORK:
#curdir=${PWD##*/}

 ls -lh $DESTFILE
#ls -1 RUN0_* | grep -v bz2 | xargs -n 1 pbzip2 -v -9 
 echo "ls -1 RUN0_* | grep -v bz2 | xargs -n 1 pbzip2 -v -9 "
 echo ...  prepare ....



if [ "$curdir" = "offline" ]; then
 echo ___________________ I am on a network branch __________________
 echo $currentdir
 echo root -l
 echo " "
 echo acq\(\"acq_local.xml\"\)
 echo ...or
 echo acq\(\"acq_locnofile.xml\"\)
 echo ... press enter
 read
 echo waiting for connection onport 9302
 
 #nc6   --exec 'cat  ~/RUN$RUNNUM | pv -s `stat -c %s  ~/RUN$RUNNUM` -L 1711k' -l -p 9302
 
 pv -L 711k  $DESTFILE | nc6 -l -p 9302
 
 echo dont forget to do acq\(\"stop\"\)
 
 echo experimental...
 DIR=`lsof /home  2>/dev/null | grep "output_20" | grep "\.root$" | sed 's/  */\t/g' | cut -f 9 | xargs dirname`
 echo _____ following dirs are supspicious of the new root file  ________
 echo $DIR
 cd $DIR
 FILE=`ls -1tr out*.root | tail -1`
 echo I am in `pwd`
 echo try 
 echo acq\(\"stop\"\)
 sleep 1
 echo acq\(\"stop\"\)
 sleep 1
 echo acq\(\"stop\"\)
 sleep 1
 echo ...
 echo cd $DIR
 echo mv $FILE run$RUNNUM$FILE 
 echo ___________________ end of network branch  __________________
 echo data may be disturbed on level 1e-5
 
else
 echo ___________________ I am on a memory branch __________________
 if [ -d "$currentdir/offline" ]; then
   echo ... offline ... present
   echo .
 else
   echo ... offline ... not present ... leaving memory branch...
   echo .
   exit
 fi

 echo $RUNNUM is old name - for net transfer
 RUN2=`echo $RUNNUM | awk '{IGNORECASE=1;sub(/^0_/,"");print }'`
 RUNNUM=$RUN2
 echo $RUNNUM is new name - memory transfer
 
 OUTDIR=$currentdir/offline/run$RUNNUM$FILE
 echo cd $currentdir
 echo root -l
 echo " "
 echo ZH_data\(-1,\"$DESTFILE\",\"$OUTDIR.root\",\"zhfile_26mg.xml\",\"plugins\",\"poper\",\"definitions\"\)
 echo " "
 echo ZH_data\(-1,\"$DESTFILE\",\"$OUTDIR.root\",\"zhfile_26mg.xml\" \)
 echo " "
 echo .q
 echo .q
 echo ______ _____________ end of memory branch __________________
 echo full data have runxx pattern
fi


